### ISSUE TITLE
login.js causes program to not open

### ISSUE THREAD

**Issue by Techno-Blueberry** [SpottedSqueak/FA-Gallery-Downloader#19]
After using the program successfully I signed out of the account that was logged in and closed it. Now I can't reopen the program and the logs just say this:
```
---
[2024-08-13T07:14:31.962Z] [31m(node:22132) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)[39m
[2024-08-13T07:14:32.029Z] Database now at: v13
[2024-08-13T07:14:32.927Z] Loaded: https://www.furaffinity.net
[2024-08-13T07:14:32.950Z] TypeError: Cannot read properties of undefined (reading 'replace')
    at setUsername [90m(file:///C:/Users/iissa/Downloads/FA-Gallery-Downloader/[39m_/js/login.js:50:8[90m)[39m
    at checkIfCookiesExpired [90m(file:///C:/Users/iissa/Downloads/FA-Gallery-Downloader/[39m_/js/login.js:59:24[90m)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async checkIfLoggedIn [90m(file:///C:/Users/iissa/Downloads/FA-Gallery-Downloader/[39m_/js/login.js:74:22[90m)[39m
    at async init [90m(file:///C:/Users/iissa/Downloads/FA-Gallery-Downloader/[39m_/index.js:173:17[90m)[39m
```

**Comment by SpottedSqueak** [comment]
Should be addressed in the latest build!

**Comment by SpottedSqueak** [comment]
Gonna close, assuming it's fixed now!
