### ISSUE TITLE
Browser Download URL returns 404

### ISSUE THREAD

**Issue by ItsAlphaNeon** [SpottedSqueak/FA-Gallery-Downloader#8]
```
/home/neon/.nvm/versions/node/v22.0.0/bin/node ./index.js
(node:71298) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
utils.js:68
Database now at: v12
utils.js:68
[Warn] No compatible browser found!
utils.js:68
Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/linux64/chrome-linux64.zip
    at file:///home/neon/Documents/GitHub/FA-Gallery-Downloader/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:72:31
    at ClientRequest.requestCallback (file:///home/neon/Documents/GitHub/FA-Gallery-Downloader/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:50:13)
    at Object.onceWrapper (node:events:635:26)
    at ClientRequest.emit (node:events:520:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
```
    
    
    
The download endpoint seems to be invalid, as going to this URL in a web browser leads to a Google 404 landing page.
Platform: Ubuntu (KDE Neon)
NodeJS version: v22.0.0
Notes:
This error occurs on build executables and running the project through nodejs

**Comment by SpottedSqueak** [comment]
Oh, of course Google would change that! Ugh. I'll have to look into alternatives. Probably just need to update Puppeteer.

**Comment by SpottedSqueak** [comment]
Okay, this should be fixed in the latest release (v.1.3.0). Let me know if it works well for you. Thanks!

**Comment by ItsAlphaNeon** [comment]
It works great, thank you for your dedication and time.
